### ISSUE TITLE
[Feature] Submit the Jitsibot to Keybase

### ISSUE THREAD

**Issue by svoop** [haukened/keybase-jitsi-bot#1]
This is a very useful bot, thanks a lot!

However, it would be even more useful if it were hosted by Keybase along with the other default bots available out of the box.

Would you mind asking the guys at Keybase whether to adopt your bot?

**Comment by haukened** [comment]
Honest question: Why do you feel that would increase the usefulness of the bot? 
It's already available in the featured bots list, and can be installed alongside any of the bots.

**Comment by svoop** [comment]
Oh, jeez, I didn't see it's already included, sorry for the noise!
